# Project information
site_name: "꧁꧂Tom's Links꧁꧂"
site_description: "Tom's Links"
site_author: "Tom"
site_url: "https://links.tomekwaller.com/"

# Copyright
copyright: "&copy; 2021 peaceiris"

# Repository
repo_name: "GitHub"
# repo_url: "https://github.com/peaceiris/mkdocs-material-boilerplate"
# edit_uri: "https://github.com/peaceiris/mkdocs-material-boilerplate/edit/main/docs"

# Configuration
docs_dir: "docs"
theme:
  name: "material"
  language: "en"
  shortcuts:
    help: 191 # ?
    next: 78 # n
    previous: 80 # p
    search: 83 # s
  palette:
    primary: "purple"
    accent: "red"
  features:
    - tabs
  #font:
  #text: 'Ubuntu'
  #code: 'Ubuntu Mono'
  #icon:
  #logo: 'images/logo.svg'
  #favicon: 'assets/images/favicon.ico'

# Extensions
markdown_extensions:
  - admonition
  - codehilite
  - footnotes
  - mdx_math:
      enable_dollar_delimiter: true
  - toc:
      permalink: true
      separator: "_"

plugins:
  - search:
      separator: '[\s\-\.]+'
      lang:
        - en
  - macros:
      include_yaml:
        - data/links.yaml

# Customization
extra_javascript:
  - "https://cdnjs.cloudflare.com/ajax/libs/mathjax/2.7.6/MathJax.js?config=TeX-MML-AM_CHTML"
extra_css:
  - "assets/css/custom.css"
extra:
  manifest: "manifest.json"
  social:
    - icon: "fontawesome/brands/github-alt"
      link: "https://github.com/peaceiris"
    - icon: "fontawesome/brands/twitter"
      link: "https://twitter.com/piris314en"

# Page tree
nav:
    - Home: 'index.md'
    - Social: 'social.md'
    - Dev: 'dev.md'
    - Polish: 'polish.md'
    - Utilities: 'utilities.md'
    - Spirituality: 'spirituality.md'
